### ISSUE TITLE
add level1

### ISSUE THREAD

**Issue by JuanDaBoi** [basiccube/PizzaTower2000#2]
yes

and also add the up+run+up thing

**Comment by basiccube** [comment]
I'm not adding that level in, and I have no idea what thing you're talking about at all.

**Comment by JuanDaBoi** [comment]
ok then

replace the moveset with a april 2021 moveset

**Comment by basiccube** [comment]
The moveset is staying as is, and it's already close to the april 2021 build moveset anyway.

**Comment by JuanDaBoi** [comment]
but one more thing left:

update when?
